server {
    listen 80;

    # 1. Normal web sayfası istekleri için HTML'i göster
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 2. /api ile başlayan istekleri içerideki backend-service'e yönlendir (Reverse Proxy)
    location /api/ {
        proxy_pass http://backend-service:8080/api/;
    }
}