apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todo-app
spec:
  ingressClassName: nginx
  rules:
  - host: todo.staj.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fronted-service
            port:
              number: 80
